"""add priority and due_date to task

Revision ID: 7230aac7aaa1
Revises: 3b76057ad542
Create Date: 2026-07-21 16:58:01.079538

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql  # 👈 导入 postgresql 模块

# revision identifiers, used by Alembic.
revision = '7230aac7aaa1'
down_revision = '3b76057ad542'
branch_labels = None
depends_on = None
# 1. 在外部定义 Enum 类型对象
task_priority_enum = postgresql.ENUM(
    'low', 'medium', 'high', name='taskpriority', create_type=False
)

def upgrade():
    # 2. 👈 执行 add_column 前，先显式在数据库中创建 taskpriority 枚举类型！
    task_priority_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
# 3. 添加 priority 列（将类型使用 task_priority_enum）
    op.add_column(
        'task',
        sa.Column(
            'priority',
            task_priority_enum,
            nullable=False,
            server_default='medium',  # 👈 建议给现有数据加上默认值，避免 NULL 报错
        ),
    )
    op.add_column('task', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'due_date')
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###
    # 👈 回滚时删除枚举类型
    task_priority_enum.drop(op.get_bind(), checkfirst=True)
